export const lightTheme = {
  background: '#f0f0f0',
  chatBackground: '#fff',
  textColor: '#000',
  inputBackground: '#fff',
  inputBorder: '#ddd',
  buttonBackground: '#007bff',
  buttonHoverBackground: '#0056b3',
  userMessageBackground: '#d1e7dd',
  responseMessageBackground: '#f8d7da',
  sidebarBackground: '#fff',
  sidebarText: '#000',
  sidebarHoverBackground: '#e0e0e0',
  headerBackground: '#f8f9fa',
};

export const darkTheme = {
  background: '#181818',
  chatBackground: '#282c34',
  textColor: '#fff',
  inputBackground: '#181818',
  inputBorder: '#555',
  buttonBackground: '#61dafb',
  buttonHoverBackground: '#21a1f1',
  userMessageBackground: '#4caf50',
  responseMessageBackground: '#f44336',
  sidebarBackground: '#20232a',
  sidebarText: '#fff',
  sidebarHoverBackground: '#333',
  headerBackground: '#343a40',
};
